name: sida_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #firebase: ^9.0.1
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  firebase_database: ^7.2.1
  google_maps_flutter: ^2.0.6
  flutter_svg: ^0.22.0
  geolocator: ^7.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Thin.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Light.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
    - family: SpoqaHanSansNeo-Regular
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
    - family: SpoqaHanSansNeo-Bold
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
